name: App EAS Build

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "EAS profile to use (preview or production)"
        required: true
        default: "preview"
      platform:
        description: "Platform to build (ios, android, or all)"
        required: true
        default: "all"
  push:
    tags:
      - "app-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Verify Expo token
        run: |
          if [ -z "${EXPO_TOKEN}" ]; then
            echo "EXPO_TOKEN is not set"; exit 1;
          else
            echo "Expo token present."
          fi
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: EAS Build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          API_URL: ${{ vars.API_URL }}
        run: |
          PROFILE="${{ github.event.inputs.profile || 'preview' }}"
          PLATFORM="${{ github.event.inputs.platform || 'all' }}"
          if [ "$PLATFORM" = "all" ]; then
            eas build --platform all --profile "$PROFILE" --non-interactive
          else
            eas build --platform "$PLATFORM" --profile "$PROFILE" --non-interactive
          fi

      - name: Output build URLs
        run: |
          echo "Builds triggered in EAS. Visit https://expo.dev/accounts to monitor."
